[project]
name = "llm-ir"
version = "0.0.2"
description = "Core message IR for LLM pipelines"
authors = [{ name="Mathis Siebert" }]
requires-python = ">=3.11"

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

