[project]
name = "llmir"
version = "0.0.5"
description = "Core message and tool IR for LLM pipelines"
authors = [{ name="Mathis Siebert" }]
requires-python = ">=3.11"
dependencies = [
    "pydantic>=2.0"
]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"